### ISSUE TITLE
HTTPBodyStream not opening.

### ISSUE THREAD

**Issue by brennick** [AliSoftware/OHHTTPStubs#109]
I followed the instructions here: https://github.com/AliSoftware/OHHTTPStubs/wiki/Testing-for-the-request-body-in-your-stubs#a-transparent-workaround

And when I call the following code:

    request.HTTPBodyStream!.open()
    let jsonObject = NSJSONSerialization.JSONObjectWithStream(request.HTTPBodyStream!, options: NSJSONReadingOptions.allZeros, error: &error) as! [String : AnyObject?]

I keep getting the error saying `Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSJSONSerialization JSONObjectWithStream:options:error:]: stream is not open for reading'`

It should be working since the stream is not nil and I have opened it, but I can't seem to get it to actual open for reading.

**Comment by AliSoftware** [comment]
Never tried that before so not sure, but it seems like you are trying to
read from `request.HTTPBodyStream`, and since it's the *request*, so the
data being sent, I bet it's an NSOutputStream, only intended for writing,
not an NSInputStream we can read from.
So it seems normal to me that you get that kind of error telling that the
steam is not open for reading (but only for writing).

(The issue is probably not related to OHHTTPStubs btw)
Le mar. 11 août 2015 à 20:50, Conner Brennick <notifications@github.com> a
écrit :

**Comment by newlix** [comment]
If the workaround in wiki is not working,  please remove it .
Thank you.

https://github.com/AliSoftware/OHHTTPStubs/wiki/Testing-for-the-request-body-in-your-stubs#a-transparent-workaround
```
A Transparent Workaround
Open and then drain the `HTTPBodyStream`. You've just recovered the `HTTPBody` as a big bag o' bytes!

If you're pulling in JSON, this gets even easier: `open` the stream, then call `+[NSJSONSerialization JSONObjectWithStream:options:error:]`. The deserializer will take care of draining the stream and spitting out JSON for you.
```

**Comment by AliSoftware** [comment]
:astonished: I'm not the one who wrote that in my wiki! Will check this out.

**Comment by AliSoftware** [comment]
@jeremy-w As you're the one who added that in my Wiki, could you explain how you made it work (or if you tested it at all), given that it doesn't seem to work the the people commenting in this issue?

**Comment by jeremy-w** [comment]
@AliSoftware I wrote it up only after I got it working in some project, so it's not an untested workaround. It's been a while though, so I'd have to do some digging to surface the code in question.

What immediately leaps to mind on reading the original post is that `NSStream` is an async API, so after asking it to `open`, you might need to listen for the `NSStreamEventOpenCompleted` event before you can read from it in order to play by the rules of its state machine. (That said, `CFStreamRead` is documented as blocking till the `open` has finished.)

It's also possible that framework changes since I used the workaround have broken it.

**Comment by AliSoftware** [comment]
Thx for the feedback @jeremy-w :+1: 
Keep us posted :wink:

**Comment by markst** [comment]
I seem to be able to check the body by serialzing the `httpBodyStream`
```swift
OHHTTPStubs.stubRequests(passingTest: { (request) -> Bool in
    guard let httpBodyStream = request.httpBodyStream else { return false }
    do {
        httpBodyStream.open()
        let requestBody = try JSONSerialization.jsonObject(with: httpBodyStream, options: [])
        print("requestBody",requestBody)
    } catch let error as NSError {
        print("error: \(error.localizedDescription)")
    }
```

#52
