### ISSUE TITLE
Questions about using HTTPStubs

### ISSUE THREAD

**Issue by mikelupo** [AliSoftware/OHHTTPStubs#110]
I'm very recently using your HTTPStubs project. 
Thank you for providing this. It's the only way that I've found where I can call invoke the same REST URL and expect different results. Most other mocking frameworks are 1:1.

What I observe at test runtime:
1) My app makes several requests besides the one for Register. (i.e. one to facebook, among others)
2) The test fails with 404 errors in my logs because I believe that OHHTTPStub is either redirecting on the wrong URL or worse, it's injecting the JSON data on a URL that it should not be mocking (ie. facebook).

Questions:
- What's the proper way to debug what OHHTTPStubs is mocking on? I want to make sure it's doing what we expect when we expect it.
- Can I use it with request.URL.absoluteString as depicted below? I would think that it does not matter so long as the parameter evaluates to true.

Notes: I am using this with the call for waitForNotificationName from: [KIF](https://github.com/kif-framework/KIF). It just helps with the async timing as the tests appear to exit before the callback is given. The SEND_UITEST_NOTIFICATION is just a macro I've written that fires the notification.
==== Implementation ==== 

    //declare the stub
    [OHHTTPStubs stubRequestsPassingTest:^BOOL(NSURLRequest *request { 
        return [request.URL.absoluteString isEqualToString:@"https://1.2.3.4:443/Path/to/Register"];
        } withStubResponse:^OHHTTPStubsResponse*(NSURLRequest *request) {
       NSDictionary* obj = @{ @"key1": @"value1", @"key2": @[@"value2A", @"value2B"] };
       return [OHHTTPStubsResponse responseWithJSONObject:obj statusCode:200 headers:nil];
    }];

    __block BOOL testStatus = NO;
    __block NSString *testMessage = @"";
    [system waitForNotificationName:@"hello" object:nil whileExecutingBlock:^{
    //Here I am invoking the UNIT of code that we wish for OHHTTPStub to inject the URL responses for.
    [MASKED registerUser:@"mikey" password:@"testing123" completion:^(BOOL status, NSString *localizedErrorMessage) {
        testStatus = status;
        testMessage = localizedErrorMessage;

        //so the test does not exit prematurely
        SEND_UITEST_NOTIFICATION(@"hello", 0);
        }];
    }];

**Comment by AliSoftware** [comment]
> 2) The test fails with 404 errors in my logs because I believe that OHHTTPStub is either redirecting on the wrong URL or worse, it's injecting the JSON data on a URL that it should not be mocking (ie. facebook).

That will only happen if:

* Either your test in the `stubRequestsPassingTest:` block is not correct (like if your returned `YES` for every request so that the stub would be triggered for all requests). But you seem to do proper tests like `[request.URL.absoluteString isEqualToString:…]` so doesn't seem to be the case here
* Or you forgot to remove your stubs from the previous Unit test before starting the next test, so the stub setup for test 1 will still be active when test 2 runs. [see that article in my wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki/Remove-stubs-after-each-test)

> * What's the proper way to debug what OHHTTPStubs is mocking on? I want to make sure it's doing what we expect when we expect it.

You can use `onStubActivation:` to log every time a stub is activated. See [here in the detailed usage examples in my wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki/Usage-Examples#name-your-stubs-and-log-their-activation) too

> * Can I use it with request.URL.absoluteString as depicted below? I would think that it does not matter so long as the parameter evaluates to true.

Yes, that's actually the most common usage.


Don't hesitate to consult my help articles in my wiki that could give you a lot of tips.

**Comment by mikelupo** [comment]
Thanks for the clarifications. And especially the quick reply.
I've been all over your wiki. It's helped me get thus far.

Turns out that the problem is actually in our app software with the "special" target configuration that's specific to unit testing. 
When I resolved it the 404 went away. 


Thanks again,
Mike


-----Original Message-----
