### ISSUE TITLE
Swift usage breaks in XCode 7 beta 5

### ISSUE THREAD

**Issue by bruceflowers** [AliSoftware/OHHTTPStubs#112]
This usage (from the examples) now breaks:

OHHTTPStubs.stubRequestsPassingTest({$0.URL!.host == "mywebservice.com"}) { _ in
  // return a stub...
}

The compiler no longer likes shorthand arguments in this context, and after making this more explicit by changing the first closure to accept "request -> Bool in", it complains about converting the boolean returned. At one point in my exploration it started to insist that comparing two strings using "==" is not allowed. 

I understand Apple breaks things frequently with swift during betas, but perhaps you can take a look?

**Comment by AliSoftware** [comment]
Thanks @bruceflowers for the info.

It seems that Xcode 7b5 is a bit broken when working with Objective-C booleans. Typically, it sees the various blocks of my API as returning `ObjCBool` instead of a simple `Bool`, and it seems like those times are not converted to one another transparently anymore :disappointed: 

So the solution for now is to wrap the value returned by your test block inside `ObjCBool(…)` to convert it to `ObjCBool` type explicitly.

```
OHHTTPStubs.stubRequestsPassingTest({ ObjCBool($0.URL!.host == "mywebservice.com") }) { _ in
  // return a stub...
}
```

I hope this is only a bug in Xcode 7b5 and not intended behavior to force us to cast to `ObjCBool` manually. I'll take that into account when I got time to implement #111 that would expose helpers for an even better Swift API, and already updated the wiki.

Thx for your feedback :wink:

**Comment by bruceflowers** [comment]
Thanks for your quick response, this worked for me. I agree with you, it's ugly to have to do this and if this was intentional on Apple's part, I'd love to know what the rationale was.

**Comment by AliSoftware** [comment]
Xcode 7 beta 6 just went out and in the release notes it's explicitly stated this:

> C typedefs of block types are now imported as typealiases for Swift closures. The primary result of this is that typedefs for blocks with a parameter of type BOOL are now imported as closures with a parameter of type Bool (rather than ObjCBool as in the previous beta). This matches the behavior of block parameters to imported Objective-C methods. (22013912)

So it appears that this was a glitch in the previous beta and has been solved.

I'm reopening the issue in order not to forget to check it when I got the time to download the latest beta and try it, and restore the previous examples without wrapping everything in `ObjCBool(…)`.

**Comment by AliSoftware** [comment]
Just confirmed that Xcode 7b6 fixed that `ObjCBool` strange stuff. no need for it anymore.

Reverted the changes in the Wiki to use plain `Bool` now, pffeeew :)
