### ISSUE TITLE
Xcode 7 warning

### ISSUE THREAD

**Issue by keith** [AliSoftware/OHHTTPStubs#116]
I'm seeing this warning in our project with Xcode 7. I can't reproduce it in the example projects in this repo, but I figured you might know how to fix it.

<img width="267" alt="screen shot 2015-09-09 at 17 07 51" src="https://cloud.githubusercontent.com/assets/283886/9777150/5d095dc0-5715-11e5-9e6f-eeb57f0c1532.png">

**Comment by AliSoftware** [comment]
Thanks @keith for the feedback.

This seems very strange, as I fixed it recently by adding the designated init [in this commit in july](https://github.com/AliSoftware/OHHTTPStubs/commit/308579e2a90b58c59d34a18eb489addea90feae2)

Are you sure you're using the latest version of `OHHTTPStubs` in the project where you have that warning? The fix was included back in 4.1.0 so if the warning is still there even in 4.1.0 and 4.2.0 then I'm still missing something…

**Comment by keith** [comment]
Ah yep sorry, I was pinning to an older version. Thanks!
