### ISSUE TITLE
my own apps; pbxproj file keeps getting updated with OHTTPStubs .xctest lines when building

### ISSUE THREAD

**Issue by mikelupo** [AliSoftware/OHHTTPStubs#117]
Is this something in one of your test schemes that is causing this?

I have OHTTPStubs included as a sub project of my App project. 
Note: We are not allowed to use cocoapods, nor are we allowed to check binary (lib) files into git. So when we use third party libraries, we have to include them in our source tree directly and build them at compile-time.

Example of my hierarchy:
MyProject.xcodeproj
--my project files
-- ...
----Test Folder
--------TestFrameworksFolder
------------ OHHTTPStubs.xcodeproj
---------------- OHHTTPStubs files/folders at this level
------------ KIF.xcodeproj
---------------- KIF files/folders at this level

In my Test target's BUILD SETTINGS in XCode:
Test Target dependencies are:
 --OHHTTPStubs iOS Static Lib
--KIF
--myAppUnderTest

Linked in with:
--libOHHTTPStubs.a
--libKif.a
--ioKit.a

There are NO OHTTPStubs sources getting compiled directly in the test target (would not compile as it would be double declared)

What happens is that when I build my test target, I get various updates to my own pbxproj file which is causing us some headaches.

__Example of a few diffs in my app's pbxproj file.__

<img width="840" alt="screen shot 2015-09-18 at 11 07 05 am" src="https://cloud.githubusercontent.com/assets/8654915/9962801/a67f4000-5df5-11e5-9aae-a97be9281d8b.png">

<img width="844" alt="screen shot 2015-09-18 at 11 09 34 am" src="https://cloud.githubusercontent.com/assets/8654915/9962856/fd49e282-5df5-11e5-90f8-9aea00a5df0f.png">

I do not have this issue with KIF, only OHHTTPStubs.
Thoughts?

**Comment by AliSoftware** [comment]
I think that's because I renamed targets at some point in the lifetime of OHHTTPStubs' project evolutions,  (like I renamed "OHHTTPStubs iOS Tests" renamed to "OHHTTPStubs iOS Lib Tests" when I introduced the dynamic framework version to make the name of the target more clear) and probably Xcode didn't update it everywhere it should have in the `OHHTTPStubs.xcodeproj/*pbxproj` files and kept the old name at some places in the pbxproj, which it updates only at compile time in some circumstances… (that's just a guess but I've see that behavior of Xcode before).

Care to post a diff to list me all the modified files so I can see where Xcode missed them? Or provide a sample project to reproduce the issue so I can check the diffs myself?

Thx

**Comment by mikelupo** [comment]
It would be labor intensive I think to produce a project and work out reproducing instructions. 
With that tidbit of history, I might be able to just do a find/replace in the project file and submit a PR.


I'll have a look
Thanks!



-----Original Message-----

**Comment by AliSoftware** [comment]
Versions 4.2.1 and 4.3.0 have been pushed with the project fixed, so you shouldn't have the issue anymore!
