### ISSUE TITLE
Add Swift helper to Mac target too

### ISSUE THREAD

**Issue by ikesyo** [AliSoftware/OHHTTPStubs#123]
I'd like to use the Swift helper not only for iOS, but also for Mac. However, since the library's deployment target of Mac target is 10.7+, `.swift` files cannot be used for the target (Swift is available from 10.9).

Do you have any plan to update the deployment target to 10.9+?

__EDIT:__ I'm using Carthage, not CocoaPods.

**Comment by billibala** [comment]
I use git submodule. Right now, modified my local copy to include the missing swift file

**Comment by AliSoftware** [comment]
Yeah I thought about it and didn't add the Swift helper in OS X because it would force to bump the Deployment Target for the whole framework, so people still wanting to use the framework on OS X 10.8 even if they were not interested in the Swift Helper wouldn't be able to use it anymore.

I'll probably gonna modify the `Podfile` so that the minimum deployment target for OS X will be set to `10.9` in the `Swift` subspec, but kept at `10.7` for the other subspecs, which would definitely solve the issue for people integrating with CocoaPods.
But I don't think there is a solution for Carthage, as Carthage is kinda strict and forces us to have everything configured once and for all in Xcode without any option for opt-in or opt-out of features like this Swift addition (and I don't want people still targeting 10.8 to not be able to use `OHHTTPStubs` anymore because of a feature they won't use anyway).

**Comment by ikesyo** [comment]
Thanks for your answer, I understand the situation and your support policy for older platforms. I'll give up to use it now.
