### ISSUE TITLE
Missing OHHTTPStubsSwift.swift file when installing with Cocoapods

### ISSUE THREAD

**Issue by kremizask** [AliSoftware/OHHTTPStubs#135]
I used cocoa pods to install the latest version (4.5.0) but OHHTTPStubsSwift.swift is not included in my pod.

**Comment by AliSoftware** [comment]
Hi @kremizask.

What's your current `Podfile` like?

The `OHHTTPStubsSwift.swift` file is part of the opt-in `Swift` subspec, so [as explained here in the README](https://github.com/AliSoftware/OHHTTPStubs#in-swift), you need to explicitly list it in your `Podfile`if you want to have it:

```ruby
use_frameworks!
…
target '…' do
  pod 'OHHTTPStubs'
  pod 'OHHTTPStubs/Swift'
end
…
```

The [default subspec](https://github.com/AliSoftware/OHHTTPStubs/blob/master/OHHTTPStubs.podspec#L36-L44) only contains the Core of `OHHTTPStubs` + the `NSURLSession`, `JSON` and `OHPathHelper` subspecs. If you want other subspecs you have to list them explicitly in your project's `Podfile`.

That's because using Swift with CocoaPods requires to use pod frameworks, which requires targeting iOS8+, and not everyone can afford to only target iOS8+ for their projects yet.  
That's why it's still an opt-in feature. This way, people not using Swift can still keep a deployment target as low as iOS5+ on their project if they need to.

**Comment by kremizask** [comment]
Thank you very much! Adding the /Swift subspec indeed resolved the issue for me. I wasn't aware of how subspecs worked and I naively assumed they were supposed to be included automatically via pod install.

**Comment by AliSoftware** [comment]
Well, in some pods, especially ones that don't explicitly specify a default subspec, indeed just writing `pod 'ThePodName'`generally brings all subspecs by default.

On other pods, like `OHHTTPStubs`, a default subspec is defined, and the other subspecs are opt-in and you need to explicitly specify them to fetch them.

Glad it solved your problem ;)
