### ISSUE TITLE
Stub requests with a file documentation improval

### ISSUE THREAD

**Issue by vicmosin** [AliSoftware/OHHTTPStubs#149]
is it somehow possible to improve the docs with more detailed information about actions should be performed in order to make it work? Currently I receive file not found error...

**Comment by AliSoftware** [comment]
What exactly would you like to be improved?

If you receive a File Not Found error probably this is because the file is not found at the path you gave (so you probably gave a wrong path) isn't it?
(But I can't help without seeing the code you used :wink:)

Note that you can make a PR to improve the doc if you find something not clear enough.

**Comment by vicmosin** [comment]
I use the snippet you used in docs:
```
stub(isHost("mywebservice.com")) { request in
  return OHHTTPStubsResponse(fileAtPath:OHPathForFile("wsresponse.json", self.dynamicType)!
    statusCode:200 headers:["Content-Type":@"application/json"])
}
```
but don't know which actions should I do in xCode project itself in order to make the file "visible" to `OHPathForFile` method

**Comment by AliSoftware** [comment]
Simply add it to your Test target. Like you would do for any other file you would want to bundle in your test target for it to access (i.e. that's not specific to `OHHTTPStubs`, that's classic Xcode step of adding a file to a target)
