### ISSUE TITLE
Multiple requests with asynchronous calls

### ISSUE THREAD

**Issue by vicmosin** [AliSoftware/OHHTTPStubs#150]
I try to use the approach you described in order to simulate multiple responses:
```
var calls = 0
stub(isHost("some.com")) { _ in
    calls += 1
      
    switch calls {
    case 1:
        return self.fixtures.root()
    case 2:
        return self.fixtures.child()
    default:
         return self.fixtures.error()
    }
}
```
where every `fixtures.*` return an `OHHTTPStubsResponse` instance.

My code is also asynchronous so I do:
```
let expectation = self.expectationWithDescription("request should succeed")
var test: Dictionary<String, AnyObject>?
traverson.follow("some").get { result in
      test = result.dictionary
      
      expectation.fulfill()
}
self.waitForExpectationsWithTimeout(self.timeout, handler: nil)
```

And I do `OHHTTPStubs.removeAllStubs()` on `tearDown` as well.

The code that I test makes exactly two calls. The problem is stub responses fine for the first time, but the second time there is no any response.. Any ideas?

P.S. The urls that I try to reach are different, btw. I.e. first call is to `http://some.com` and second to `http://some.com/some/`

**Comment by AliSoftware** [comment]
If you put a breakpoint in the closure of your `stub(isHost("some.com")) { _ in … }` does it get called on every request? Are you sure the second request is really triggered?

**Comment by vicmosin** [comment]
That's a point that second request is not triggered, but definitely called

**Comment by AliSoftware** [comment]
Ok so that's not a case like the `calls` variable being const-captured by the closure and being always 1 in the context of the closure, returning the same stub every time, but more a case like the request is not caught the second time.

If the closure is not called it's either because the request is not sent or because the condition is the `stub(…)` is not met. For example the second call does not use the host you think it does, because you made a typo in your code or sthg.

To debug it you could create a "catching-all-stub" and put a breakpoint in it to investigate your code further. For example:

```swift
// A stub catching *all* requests
stub(true) { request in
  print("Request = \(request)")
  print("Request host = \(request.URL.host)")
}

// Then your normal stub, which takes precedence if the isHost() condition is met
var calls = 0
stub(isHost("some.com")) { _ in
    calls += 1

    switch calls {
    case 1:
        return self.fixtures.root()
    case 2:
        return self.fixtures.child()
    default:
         return self.fixtures.error()
    }
}
```

The first `stub(true)` will catch every request unless those previously caught by the `stub(isHost("some.com"))`. So if the second call is not caught by your stub, the `stub(true)` will capture it. You could then see what is printed in the console.

If the `stub(true)` closure is not called at all, that definitely means the second request is not even sent. If the `stub(true)` closure is called, you will be able to investigate what host it uses and use breakpoints to see what went wrong.

**Comment by vicmosin** [comment]
Oh, you are right, the second call contained `www.*` prefix. Thanks for pointing to it!
