### ISSUE TITLE
Response with empty body

### ISSUE THREAD

**Issue by vicmosin** [AliSoftware/OHHTTPStubs#152]
I try to simulate a HTTP's `204` response without body. Both
```
return OHHTTPStubsResponse(data: "".dataUsingEncoding(NSUTF8StringEncoding)!, statusCode: code, headers: nil)
```
and 
```
return OHHTTPStubsResponse(data: NSData(), statusCode: code, headers: nil)
```
gives me `null` value as a response so I can't check for `XCTAssertNil`assertion. Is there another way?

**Comment by samirGuerdah** [comment]
Hello,

I have tested the same code you have posted and the OHHTTPStubsResponse instance created is not nil.  Can you show more code how you are doing it ?

**Comment by vicmosin** [comment]
It's not about creating nullable `OHHTTPStubsResponse` object, I guess you misunderstood me. I was talking about nullable response body within `OHHTTPStubsResponse` object.

The case is the following: I `Alamofire` to make requests, it's logics puts the response into `NSData?` instance, but if I use the examples I posted in original post, the value of that NSData is not nil, but length = 0. I am not sure if it's their issue or OHHTTPStubs's...

P.S.
I can handle it by additional checking if response.length > 0 anyway

**Comment by samirGuerdah** [comment]
Hello,

```
let data = NSData()
XCTAssertEqual(data.lenth, 0)
```

The data object is not nil but it contains no data :). 
Just test if the length of the body is equal to 0, hope that i answered your question :). 

(In OHHTTPStubsResponse i think that you can test with the dataSize property if it's equal to 0 or no).

**Comment by vicmosin** [comment]
It wasn't my question...
I'm just trying to understand: should I treat that behavior as a bug or not. Optional values were introduced exactly for these purposes and to me it looks like an issue - if data object contains no data it should be nil..

**Comment by AliSoftware** [comment]
That's intended design in `OHHTTPStubs` to not make the `NSData` optional. That is to mimic the actual behavior and design of Apple's URL Loading System. And that's because it does not make sense to make a difference between "nil = no data" and "empty NSData".

So I'm not sure why `Alamofire` accept `nil` `NSData` in its design while an empty `NSData` conceptually means the same so the input domain is over-defined and two different input exist to represent the same case. If your server replies with a `204: No Content` do you expect the `NSData` received to be `nil` or empty? Given both could match, keeping both possibilities (making it nullable) just makes cases confusing.

In fact that's also why Apple revised all their frameworks recently to annotate the Cocoa Framework and change some methods which previously returned nullable NSString, NSData or NSArray to now always return a non-nullable empty objects (empty NSString, empty NSArray, empty NSData, …) instead. Because both could represent the same but having to test both cases instead of just one every time you use the API was a PITA.

**Comment by vicmosin** [comment]
So I guess it's mostly Alamofire's issue/feature rather then OHHTTPStubs's...

**Comment by AliSoftware** [comment]
Indeed.

I wouldn't say it's a _bug_ in Alamofire, rather a different design choice. I prefer to be aligned with Apple and to avoid having multiple values representing the exact same case, but maybe Alamofire has its rationale for making it optional? Or maybe they didn't think it through yet, and asking them might trigger a debate and reflection about why they allow a `nil` `NSData` while an empty one already represent the same thing.

**Comment by vicmosin** [comment]
Just checked Alamofire's default serialization sources. They use `SerializationResult<NSData, ErrorType>` for every single serializer, so that's why final result is not nil but has a length of 0. I guess we can close the issue since it can be handled by additional check at client-side.
