### ISSUE TITLE
OHHTTPStubs isn't switching off

### ISSUE THREAD

**Issue by janglesdev** [AliSoftware/OHHTTPStubs#156]
When attempting to call `[OHHTTPStubs setEnabled:NO]` (at runtime, after having enabled them), the tests are still invoked, and a mock response is still returned.  We had to manually call `removeAllStubs` to disable OHHTTPStubs, and re-add them to re-enable stubs.

**Comment by AliSoftware** [comment]
If you're using `NSURLSession` that's normal.

`+setEnabled:` only disable stubs on the `NSURLConnection` stack (and the `sharedSession`).

But `NSURLSession` instances use `NSURLSessionConfiguration` to configure supported `NSURLProtocol` so changing supported URL protocols (which includes turning on or off `OHHTTPStubs` on that `NSURLSession`) can only be done *before* creating the `NSURLSession` with an `NSURLSessionConfiguration`.

This behavior is documented [in the library's documentation here](http://cocoadocs.org/docsets/OHHTTPStubs/4.7.0/Classes/OHHTTPStubs.html#//api/name/setEnabled:)

**Comment by engineeringman** [comment]
But the fact that I can manually remove those stubs, and re-add them proves there's a solution to be had for this issue.  While forcing the user to re-add the stubs after re-enabling OHHTTPStubs would be bad, wouldn't disabling the stubs tests when OHHTTPStubs is disabled be a valid solution?

**Comment by AliSoftware** [comment]
Probably not a good consistency solution because there would then be multiple levels of 'enable' meanings then, but might be worth considering. PR welcome if you think that would be worth it.

**Comment by engineeringman** [comment]
I'll make a PR when I have a chance.

I understand your case, but I'm not certain I agree.  It seems that OHHTTPStubs.enabled should reflect whether or not OHHTTPStubs has any influence.  So when a user disables OHHTTPStubs, the application should behave exactly as if OHTTPStubs was never installed/enabled in the first place.

**Comment by AliSoftware** [comment]
The problem is that `NSURLProtocol` doesn't allow s to know from which `NSURLSession` (thus `NSURLSessionConfiguration`) a network request comes from.

So I don't think that's even technically possible to make `OHHTTPStubs.setEnabled(_:,forURLSessionConfiguration:)` disable requests on a given configuration once the `NSURLSession` has been created. Because then the implementation of `NSURLProtocol.canHandleRequest:` would not know which session the request came from and which enable flag to check to know if the stub should be used or not depending on that enabled flag per session.

From that, if we decide to make `OHHTTPStubs.setEnabled(_:)` affect every request so that even requests from any `NSURLSession` would be disabled, there would be a great misbalance between `OHHTTPStubs.setEnabled` and `OHHTTPStubs.setEnabled(_:,forURLSessionConfiguration:)` then, because one would only install `NSURLProtocols` for a given `NSURLSession` and the other would both install it `NSURLConnection` and `NSURLSession.sharedSession` requests and act as a flag for any requests both from `NSURLConnection`, `NSURLSession.sharedSession` and `NSURLSession.sessionWithConfiguration:`.


If we do that, I'd prefer that we adapt the API to make it less messy and with clearer intent, otherwise I already see the issues/questions coming from users not understanding why one method originally only affecting `NSURLConnection` and `sharedSession` requests now also affect other requests created in a sandboxed session.

So maybe we could rename `setEnabled:` and `setEnabled:forURLSessionConfiguration:` to `setInstalled:` and `setInstalled:forURLSessionConfiguration:`, which only configure the `NSURLProtocol` installation and install OHHTTPStubs in the URL Loading System, while a new method `setDisabled:` would apply to every request and stub, whether their are from an arbitrary `NSURLSession`, the `NSURLSession.sharedSession` or from `NSURLConnection`. And remove the ambiguous `setEnabled:` and `setEnabled:forSessionConfiguration` then.

**Comment by AliSoftware** [comment]
@janglesdev I'm closing this "OHHTTPStubs isn't switching off" issue as the original issue is solve (it was more of a misunderstanding of the API than a bug) and lack of response about the API change.

But feel free to open a new PR to add that distinction between `setDisabled` vs. `setInstalled:` discussed above if you still feel it feasible and worth it, I'm still open to the idea — even if as I said I'm not sure it's technically possible with `NSURLSession` as we can't modify `NSURLSessionConfiguration`s on existing `NSURLSession` and we can't know from which `NSURLSession` is coming the request when `canHandleRequest:` is called in `NSURLProtocol` to determine if we should stub or not.
