### ISSUE TITLE
Suddenly no response returned

### ISSUE THREAD

**Issue by ogezue** [AliSoftware/OHHTTPStubs#157]
I have recognized a strange behaviour of my tests. They were working fine for weeks. Than they failed on my development machine but passed on the CI-Server. Now they are fail there also. The problem is that there is no response received that can be handled. The fixture never returns.

How can I debug this?

Here is how one of my test classes looks like:

```
import XCTest
import OHHTTPStubs
import RealmSwift
@testable import ZEventApp

class OverviewModelTests: XCTestCase {
    
    weak var httpStub : OHHTTPStubsDescriptor?
    
    override func setUp() {
        super.setUp()
    
        
        self.httpStub = stub( { request in request.URL!.absoluteString == URLs.sharedInstance.overviewItemsUrl() } ) { _ in
            let stubPath = OHPathForFile("Overview.json", self.dynamicType)
            
            return fixture(stubPath!,status: 200 ,headers:
                ["Content-Type":"application/json"])
        }
    }
    
    override func tearDown() {
        if let httpStub = self.httpStub{
            OHHTTPStubs.removeStub(httpStub)
        }
        
        super.tearDown()
    }


    func testFetchOverviewItems() {
        
        let responseArrived = self.expectationWithDescription("response of async request has arrived")
        var receivedItemList : List<OverviewItem>?
        
        
        let overviewModel = OverviewModel()
        overviewModel.fetchOverviewItemList(false, successHandler: { (itemList: List<OverviewItem>) -> () in
            
            receivedItemList = itemList
            responseArrived.fulfill()
            
            }){ (error: ErrorType?) -> () in
                log.error(error)
                XCTFail("Error in testFetchOverviewItems")
        }
        
        self.waitForExpectationsWithTimeout(5) { err in

            if let itemList = receivedItemList{
                
                XCTAssert(itemList.count == 6)
            
                for item in itemList where item.sortOrder == 99{
                
                    XCTAssert(item.sortOrder == 99)
                    XCTAssert(item.overviewID == 1)
                    XCTAssert(item.imageUrl == "imageUrlExample.png")
                    XCTAssert(item.contentUrlDE == "contentURLDE")
                    XCTAssert(item.contentUrlEN == "contentURLEN")
                    XCTAssert(item.contentUrlFR == "contentURLFR")
                    XCTAssert(item.titleDe == "TitelDE")
                    XCTAssert(item.titleEn == "TitelEN")
                    XCTAssert(item.titleFr == "TitelFR")
                    XCTAssert(item.isMarkedAsNew == true)
                    XCTAssert(item.isActive == true)
                    XCTAssert(item.isCalendar == true)
                    XCTAssert(item.isProfile == true)
                    XCTAssert(item.isLargeCell == true)
                }
            }
            else{
                XCTFail("No data received")
            }
        }
    }
```

**Comment by ogezue** [comment]
Perhaps this info helps: If I print stubs at the end of the setup method 
```
 let stubs = OHHTTPStubs.allStubs()
        print(stubs)
```

I get this here:

```
Printing description of ((OHHTTPStubsDescriptor *)0x00007fb019ee9050):
<OHHTTPStubsDescriptor 0x7fb019ee9050 : (null)>
```

is (null) ok?

**Comment by AliSoftware** [comment]
Mmh no that `(null)` seems strange indeed.

Maybe you're experiencing [this problem](https://github.com/AliSoftware/OHHTTPStubs/wiki/A-tricky-case-with-Application-Tests) and your stubs get added to one of the OHHTTPStubs class instance while the tested code use another?

**Comment by ogezue** [comment]
I think thats is not my problem. I haven't changed here something in my setup. I recognized that my build-system reports a much greater number of tests then really existing (41 existing / 471 reported). The tests that don't rely on OHHTTPStubs work fine.
Per haps you have some advice for debugging if you watch my setup method above?

**Comment by AliSoftware** [comment]
Ok so I guess your stubs are setup correctly, but the conditions probably don't match anymore.

Especially, `request.URL!.absoluteString == URLs.sharedInstance.overviewItemsUrl()` is probably never true. Which might be because you added query params, or a `/` is being aded at the end of the URL sent, or because you have `#` anchor in your URL etc.

It's generally not a good idea to compare `absoluteURLs` directly to stub. Because multiple URLs with slight differences might represent the same URI resource. Like `http://host.org/path?foo=bar&baz=qux`, `http://host.org/path?baz=qux&foo=bar`, `http://host.org/path/?foo=bar&baz=qux` and `http://host.org:80/path?foo=bar&baz=qux&#` all probably represent the same in your server (they are said to be "canonical equivalent URLs"), but comparing the `absoluteString` of each will fail.

To debug your issue, I suggest that you log all of the requests that might be captured by `OHHTTPStubs` and carefully check the differences between the compared `URL!.absoluteString`, as I bet there are some tiny subtle differences that would explain why the `==` test fail:

```swift
self.httpStub = stub( { request in
  print("Request to be sent: \(request) — \(request.URL!.absoluteString)")
  print("Will be compared to: \(URLs.sharedInstance.overviewItemsUrl())")
  let compared = request.URL!.absoluteString == URLs.sharedInstance.overviewItemsUrl()
  print("Comparison result: \(compared)")
  return compared
} ) { _ in
            let stubPath = OHPathForFile("Overview.json", self.dynamicType)

            return fixture(stubPath!,status: 200 ,headers:
                ["Content-Type":"application/json"])
        }
```

Once you've figured out what are de differences between the sent request URLs and the ones you compare them to, you can refine your comparison condition and avoid using `absoluteString` but instead compare requests by their relevant parts, like the URL host, path, query params, etc.

**Comment by ogezue** [comment]
Thank you very much for your support - that's really great.
I replaced the inside of my setUp method with your code and recognized the following:

- The body of the closure is never called
- My test fetches data from the network and compares the server response.

Is there some point in your framework where I can observe the comparison of the urls? Other ideas?

Here is my podfile - perhaps an other lib causes the problem?

```
platform :ios, '9.0'
use_frameworks!

pod 'Alamofire', '~> 3.2.0'
pod 'AlamofireObjectMapper', '~> 2.1.2'
pod 'RealmSwift', '~> 0.98.2'
pod 'KeychainAccess', '~> 2.3.3'
pod 'Mattress', '~> 1.0.3'
pod 'ReachabilitySwift', '~> 2.3.3'
pod 'SwiftyBeaver', '~> 0.3.3'
pod 'Chatto', '= 1.0.0'
pod 'ChattoAdditions', '= 1.0.0'
pod 'Attributed'
pod 'PermissionScope'

target 'MyAppTests' do
   pod 'OHHTTPStubs'
   pod 'OHHTTPStubs/Swift'
end
```

**Comment by AliSoftware** [comment]
Then if even the comparison closures are never called that means that `OHHTTPStubs` is not loaded by the time you initialize your `NSURLSession`, maybe because you do your first call with Alamofire too early — especially if you use hosted tests and create your `NSURLSession` (via your first request using Alamofire maybe?) in the `application:didFinishLaunchingWithOptions:`, which is executed just before the Test bundle is loaded in memory by Xcode/XCTest?

Especially you should take a look at issue #126 as you might have a similar setup causing a similar behavior.

**Comment by ogezue** [comment]
That's it! The problem was that I had a automatic login with credentials from the keychain in my delegate... I think I have to redesign my test / application architecture.
Perhaps it is something to add to your documentation?

Thank you ver much!
