### ISSUE TITLE
Artefacts built with Xcode prior to 7.3 do not work anymore

### ISSUE THREAD

**Issue by AlexDenisov** [AliSoftware/OHHTTPStubs#162]
He there,

Just found recently that artefact I downloaded from "Releases" page do not work with Xcode 7.3 because of Swift 2.2 and ABI compatibility.
I rebuilt the framework using new Xcode and issue has gone.
It would be nice if you can upload another build, e.g. something like `OHTTPStubs.framework-Swift-2.2.zip`.

Thank you.

**Comment by AliSoftware** [comment]
Hello,

Thanks for letting me know.

Problem is, the artefact uploaded in the GitHub Releases is there for Carthage compatibility. And Carthage explicitly expects it to be named `NameOfTheLibrary.framework.zip` explicitly; so I don't see how I can make it work for Carthage for both Swift 2.1 and 2.2, as I will have to choose which one to name it so that Carthage should pick it, and that choice is impossible as it depends on what Swift version people are using.
So instead I think I'll have to release a new version… with no real new feature but just to allow Carthage users to pick one or the other :unamused: 

_That's one reason why I don't recommend using Carthage which rely on Swift ABI compatibility which we know will break, and encourage using other solutions like CocoaPods instead._

**Comment by iamtomcat** [comment]
You could also not include a prebuilt framework. While it makes it slower for people as they would have to wait for carthage to build it, but it would fix the incompatibility issue.

**Comment by AlexDenisov** [comment]
@AliSoftware I can't say what is better for Carthage, but newly built framework in any form will work for us, since we use custom solution for managing dependencies.

@iamtomcat I think it's still helpful to have both options.

**Comment by AliSoftware** [comment]
@AlexDenisov unfortunately given how Carthage works we can't both propose the zip for Carthage to download and propose the option for Carthage to build from source. Either the zip is there either it isn't but we can't have multiple zips for Carthage to use and if there is a zip Carthage won't build from source. I know, right?

**Comment by AliSoftware** [comment]
I think the only reasonable option here is what @iamtomcat suggests: for the next release (expected in a few days after merging the last recent submitted PRs) I won't include any zip at all so that Carthage will be forced to rebuild from source in order to be sure it's compatible with both Swift 21 and 2.2 and avoid ABI incompatibility.

**Comment by AlexDenisov** [comment]
@AliSoftware TIL :)
The way you choose will work us as well.
Thank you for working on the problem.

**Comment by iamtomcat** [comment]
Just as a workaround atm. I've added
`github "AliSoftware/OHHTTPStubs" "6d305e8a834cb78f7e07433b9a9ae13f8c172910"`
which is just the 4.8.0 commit itself.

**Comment by skovatch** [comment]
For Carthage you could use `carthage bootstrap --no-use-binaries` and it will rebuild from the source code and ignore the included zip.

**Comment by kwandrews7** [comment]
We've imported this project manually not using pods or carthage. I may just be a newb here, but could you outline what "build" I would need to do or what files I need to update to get this working with Xcode 7.3? I've tried selecting the OHTTPS schemes and building them and that still does not resolve the errors.

**Comment by AliSoftware** [comment]
@kwandrews7 I believe your problems ar totally unrelated: if you've imported the `OHHTTPStubs` **project** manually, then you're building them from source; so in this case this is not related to build artefacts at all (you might need to "clean" before "build" though, but as for any other project, and this has nothing to do).

The future release — that I plan to do today — will not contain pre-build artifacts to avoid compatibility issues between Swift 2.1 and Swift 2.2, and so that Carthage build them back from source. Having a pre-build framework relying on a specific Swift runtime is not recommended by Apple anyway (at least not until the Swift ABI is stable)

**Comment by AliSoftware** [comment]
Version 5.0.0 has been released to CocoaPods.

The GitHub release 5.0.0 has also been created, but this time I didn't include the prebuilt framework in order to avoid Swift Runtime ABI incompatibility risks for Carthage users during the transition from Swift 2.1 to Swift 2.2

**Comment by iamtomcat** [comment]
Cool, thank you.
