### ISSUE TITLE
Umbrella header not found using XCode 7.3 with Carthage.

### ISSUE THREAD

**Issue by kanekin** [AliSoftware/OHHTTPStubs#168]
I am getting error when building my test using Xcode 7.3 (7D175), Carthage 0.15.2 and OHHTTPStubs v5.0.0.
`OHHTTPStubs` is built by `carthage update --platform iOS`.
The error message is :
```
{PROJECT_DIR}/Carthage/Checkouts/OHHTTPStubs/OHHTTPStubs/Supporting Files/module.modulemap:2:19: Umbrella header 'OHHTTPStubsUmbrella.h' not found

Could not build Objective-C module 'OHHTTPStubs'
```
Looking into the `/Supporting Files` dir, `OHHTTPStubsUmbrella.h` exists.

I have read #132 , #127 , but I could not manage to fix the issue. 

I noticed that v5.0.0 was the only release without having prebuilt framework. And I am a bit surprised that it is complaining about a file located in Carthage/Checkouts folder, since to my understanding of Carthage, the files that should matter during build should be only in Carthage/Build dir. 

Could you kindly help me to spot the issue?

**Comment by AliSoftware** [comment]
Strange behavior indeed.
I'm not a Carthage user myself, so I don't really understand why it can't find the file in `/Supporting Files` and why it searches in `Carthage/Checkouts`, I'm not sure how all this thing with Carthage is supposed to work tbh. Maybe you should ask on the Carthage repo, or maybe someone more experienced with Carthage inner behavior could help?

---

I didn't link the rebuild framework for version 5.0.0 because Carthage has another issue: due to how it works and make frameworks depend on the Swift Runtime libraries, using Carthage breaks when the Swift ABI changes, which is what happened with Xcode 7.3, which is embedding a new version of Swift and the Swift Runtime compared to Xcode 7.2.

So I couldn't ember a Carthage framework that would be both compatible with Xcode 7.2 (for people who didn't already upgrade yet, possibly due to the depreciation warning it generates) *and* Xcode 7.3 and the preferable solution was to _not_ provide a pre-build framework so as to force Carthage to rebuild the library from source, hence matching the Xcode version — and more importantly the Swift version used — by the user's project.

_(To my understanding, that's a flaw in Carthage foundation itself, relying on / expecting the Swift ABI to be stable whereas Apple explicitly said that it wasn't — that's also why I prefer to rely on SPM or CocoaPods which build libs from source)_

**Comment by AliSoftware** [comment]
Any luck with asking on StackOverflow or on the Carthage repo to have more information about think kind of issue?
As I said, I'm not sure about what is wrong but as I'm not a Carthage user and don't really get how Carthage works and why it can't find the umbrella header, I'm not sure I can help, would love to see this issue resolved though.

**Comment by kanekin** [comment]
@AliSoftware Hi, thanks for the reply. I was on a vacation, I haven't got around to post the questions yet. I think I can post the questions on Carthage repo tomorrow. I will keep you updated.

**Comment by kanekin** [comment]
@AliSoftware I have solved the problem.
I looked through the settings for my test target, and I found `../**` in ```User Header Search Paths```.
This was causing XCode to look everything under the parent directory of the test directory.
I removed `../**` from ```User Header Search Paths```, and the test was built successfully.

Thanks for your help and excuse me for not checking my settings more carefully in the first place.

**Comment by AliSoftware** [comment]
Oh that's awesome thanks for the feedback! Sorry not to have been more helpful with that.

Do you know where that `../**` came from? Did you or one of your coworker add it to your project at some point manually? Or do you think it was added by some external tool behind the scenes?

Anyway thanks for the feedback, I'm gonna close the issue as it was not related to my lib but to your project configuration after all!
