### ISSUE TITLE
OHHTTPStubs seems never stubs my requests :-?

### ISSUE THREAD

**Issue by ivanruizscm** [AliSoftware/OHHTTPStubs#176]
Here is a simple project with the issue:
www.ruiznadal.com/TestingOHHTTPStubs.zip

And the code is basically:
```
    func testFetchOverviewItems() {
        myStub = stub(isHost("www.google.com")) { request in
            let stubPath = OHPathForFile("stub.txt", self.dynamicType)
            return fixture(stubPath!, headers: ["Content-Type":"text/plain"])
                .requestTime(0.0, responseTime:OHHTTPStubsDownloadSpeedWifi)
        }
        var finalResult: String?
        api.test { (result) in
            finalResult = result
        }

        expect(finalResult).to(equal("works"))
    }


    func test(callback:(String) -> Void) {
        request(.GET, API.url)
        .responseJSON { (response) in
            callback("dont work")
        }
    }

```

**Comment by AliSoftware** [comment]
I just tested your sample code provided. The stubbing works perfectly.

But what makes you think that it doesn't work is that your `test` method always calls `callback("dont work")` whatever the `request(.GET, API.url).responseJSON` returned. So even if you stub your request so that it returns stubbed data, your `api.test { … }` callback will always be called with a `result` having the `"dont work"` value as that's the hard-coded value that you return every time.

Besides, you use Alamofire's `.responseJSON` which expects the data received from the network (or from your stub in your case) to be JSON — and would fail if it's invalid/un-parsable JSON — but if you stub with the string "works" this won't be parsable as JSON so Alamofire will fail. Which is another reason why you don't manage to stub

Finally, I'm not a Quick/Nimble user myself, but are you sure that `expect(finalResult).to(equal("works"))` does wait *asynchronously* for the result?

**Comment by AliSoftware** [comment]
As a proof that `OHHTTPStubs` is stubbing as it should, I managed to make your code work by changing these in your code:

1) I change your `stub.txt` file to simply be `{ "foo": "works" }`, so at least it is valid JSON, and would make sense for your stub (otherwise `.responseJSON` would fail to parse the stubbed response)

2) Make `api.test` return something that actually depend on the response instead of a hard-coded value

```swift
func test(callback:(String) -> Void) {
        request(.GET, API.url)
        .responseJSON { (response) in
          let jsonDict = response.result.value as? [String:String]
          callback(jsonDict?["foo"] ?? "")
        }
    }
```

3) Make your test asynchronous

As `expect(finalResult).to(equal("works"))` doesn't wait for the request to be finished before testing, so it checks for equality too soon and in a synchronous manner, which doesn't make sense for network calls which are asynchronous by nature. So instead, change it to:

`expect(finalResult).toEventually(equal("works"))`

See https://github.com/Quick/Nimble#asynchronous-expectations for more info (that's where I found it as I never used Quick/Nimble before)

**Comment by ivanruizscm** [comment]
thx you so much
