### ISSUE TITLE
Is there a way to do a "Man in the middle"?

### ISSUE THREAD

**Issue by mikelupo** [AliSoftware/OHHTTPStubs#183]
I have a situation where I need valid device credentials from the server, but we need to "massage" some response data.
Is there a way to forward the request to the server, capture the response as it comes back, then make changes to it (hence, "Man in the middle") before sending it on to the requestor?

Thanks in advance

**Comment by AliSoftware** [comment]
Hi there,

There is no official way to do that the way `NSURLProtocol` works in Foundation.
But you might be able to trick it by using `NSURLProtocol.propertyForKey(_:, inRequest:)` and `NSURLProtocol.setProperty(_:, forKey:, inRequest:)` methods — see [here in the wiki for an example usage](https://github.com/AliSoftware/OHHTTPStubs/wiki/Testing-for-the-request-body-in-your-stubs#storing-requests-meta-data-to-write-easier-tests)

My idea for your use case, the idea would be to stub requests that have no value set for an arbitrary property `ByPassStubs`, and in the stubbing block, duplicate the `NSURLRequest`, associate to it a value to the `ByPassStubs` property, and re-send it. This time the secondary request won't be stubbed as you et the flag, and once the request is finished, you could build your real stub response from that.

Note that the secondary request would probably need to be sent in an asynchronous way because you won't be able to wait for a completion block to be called to return from the `stub` method.

**Comment by AliSoftware** [comment]
Here is a *draft* of what it might look like.
Quickly typed directly in GitHub, so:

* not tested at all
* invokes synchronous network requests which is bad (maybe make it run on a dedicated thread + runloop instead?)
* the function sync-sending the real request only returns the data, you might tweak this to return the statusCode and headers as well so you can adapt to your needs

But basically it's just to show you the idea.

```swift
private let kFlagKey = "ShouldBypassStubs"
let hasBypassFlag: OHHTTPStubsTestBlock = {
  NSURLProtocol.propertyForKey(kFlagKey, inRequest: $0) != nil
}

private func sendSynchronousRequest(request: NSURLRequest) -> NSData? {
  // Don't do this at home, kids. It's bad.
  var data: NSData? = nil
  let semaphore: dispatch_semaphore_t = dispatch_semaphore_create(0)
  let task = NSURLSession.sharedSession().dataTaskWithRequest(request) { taskData, _, error -> () in
    data = taskData
    if data == nil, let error = error {print(error)}
    dispatch_semaphore_signal(semaphore);
  }
  task.resume()
  dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER)
  return data
}

stub(isHost("mywebservice.com") && !hasBypassFlag) { req in
  let reqCopy = req.copy() as! NSURLRequest
  NSURLSession.setProperty(true, forKey: kFlagKey, inRequest: reqCopy)
  let data = sendSynchronousRequest(reqCopy)
  return OHHTTPStubsResponse.responseWithData(data, statusCode: 200, headers: nil)
}
```
