### ISSUE TITLE
Feature Request: Stream from file

### ISSUE THREAD

**Issue by mikelupo** [AliSoftware/OHHTTPStubs#187]
Is it possible for OHHTTPStubs to stream from a file? For example, a .mp4 file.
If it's not, then what would a contributor have to do in order to enable this feature?
We ask because our streaming player complains with an error when we try to stream from a file that's been stubbed. 

Thanks in advance

**Comment by AliSoftware** [comment]
When you build your `OHHTTPStubsResponse` to return in your stub, you should be able to build that response in multiple possible ways, as [this type exposes various constructors](https://github.com/AliSoftware/OHHTTPStubs/blob/master/OHHTTPStubs/Sources/OHHTTPStubsResponse.h), including:

* `responseWithData:statusCode:headers:`, which builds an `[NSInputStream inputStreamWithData:data?:[NSData data]]` then calls the internal `initWithInputStream:dataSize:statusCode:header:` constructor
* `responseWithFileAtPath:statusCode:headers:`, which builds an `[NSURL fileURLWithPath:filePath]` then call the method below
* `responseWithFileURL:statusCode:headers:` which builds an `[NSInputStream inputStreamWithURL:fileURL]`, compute the file size, then calls  the internal `initWithInputStream:dataSize:statusCode:header:` constructor

`initWithInputStream:dataSize:statusCode:headers:` is the designated initialized (that will be called in the end by any of the other convenience initializer) and which definitely takes an `NSInputStream`.

So yes, if that was your questions, you have everything to stream from a file, `responseWithFileURL:statusCode:header:` already uses `NSInputStream` and streams that content (instead of loading it all in memory at once and sending that NSData).

The only thing `OHHTTPStubs` does that your player might not like is that it adds the `Content-Length` header to the request automatically if it's not present/defined already, and if your player expects streaming content in the sense of "non-fixed-length content that might never end", maybe that additional `Content-Length` header bothers it?

**Comment by AliSoftware** [comment]
Hi. I'm gonna close this issue now due to the fact that I think I've answered your question and due to lack of response. Consider reopening if you still have pending problems about that due to OHHTTPStubs itself.

**Comment by mikelupo** [comment]
Sorry I have not had a chance to revisit this. When I do and if I should have any further issue I will reopen. 
Thank you for your careful and thought out reply!

Mike

Ps...we are using this library extensively and quite creatively I might add. We are thankful for it!
