### ISSUE TITLE
Xcode 6 still supported?

### ISSUE THREAD

**Issue by JanC** [AliSoftware/OHHTTPStubs#199]
Hi,
I'm trying to run my tests in XCode 6 but `OHHTTPStubs` don't seem to compile. 

```
OHHTTPStubsSwift.swift:30:5: error: unexpected target configuration expression argument type
OHHTTPStubsSwift.swift:32:5: error: unexpected target configuration expression argument type

```

What is the latest version that supports Xcode 6?

cheers

**Comment by AliSoftware** [comment]
I haven't tested OHHTTPStubs in a long time in Xcode 6.

Are you using Swift in your project?
How are you integrating OHHTTPStubs in your project? CocoaPods? Carthage? Manually?

I think Xcode 6 is containing a version of the compiler too old to know the Swift target compilation directives. If you're not using Swift, just don't integrate the Swift extension in your Podfile. If you need to use Swift, you'll need to use a version before those `#if` were added to the codebase to support Swift 3, because Xcode 6 is too old to know about those.

**Comment by JanC** [comment]
I'm using Carthage for the tests dependencies and all my tests are in Objective C

**Comment by AliSoftware** [comment]
No, Carthage doesn't allow conditionally include only some parts of the library, that's a limitation of Carthage itself, so you can't opt-out of the Swift extension with Carthage.
You'll either have to use CocoaPods (with the CocoaPods-Rome plugin if you want CocoaPods to work the same as Carthage and only generate the `.framework` and let you integrate all manually) or if you still want to use Carthage, you'll have to use an older version of OHHTTPStubs.

Given the [CHANGELOG](https://github.com/AliSoftware/OHHTTPStubs/releases), I think the latest version compatible with Xcode 6 is version 5.1.0, as the Swift 3 support with `#if` conditions for Swift 3.0 was added with 5.2.0.

**Comment by JanC** [comment]
ok thanks, I'll give it a try. Maybe I can just keep the compiled `.frameworks` only for the CI xcode 6 tests. 

cheers!
