### ISSUE TITLE
subspec OHHTTPStubs/Swift should have OHHTTPStubs/NSURLSession dependency

### ISSUE THREAD

**Issue by Igor-Palaguta** [AliSoftware/OHHTTPStubs#208]
Added swift api of OHHTTPStubs to project with:
```
pod 'OHHTTPStubs/Swift'
```
But stubs did not work. Spent a lot of time trying to find issue in my own code, but then adding one more dependence helped:
```
pod 'OHHTTPStubs/NSURLSession'
```
Can we add dependency 'OHHTTPStubs/NSURLSession' to 'OHHTTPStubs/Swift' subspec.

**Comment by Liquidsoul** [comment]
Hi @Igor-Palaguta,

Maybe I misunderstood your setup but it appears that you may have missed what is said in the [cocoapods part of the README](https://github.com/AliSoftware/OHHTTPStubs/blob/master/README.md#cocoapods) stating that your `Podfile` must reference both the main spec ˋOHHTTPStubs` and the swift subspec `OHHTTPStubs/Swift`.
So adding more than just the Swift subspec is the expected way to go 😉

**Comment by Igor-Palaguta** [comment]
Thanks @Liquidsoul for response. I've seen this, but nobody reads documentation - believe me) And better to add one more dependency to subspec to prevent this in future. 

```
  s.subspec 'Swift' do |swift|
    swift.ios.deployment_target = '8.0'
    swift.osx.deployment_target = '10.9'
    swift.watchos.deployment_target = '2.0'
    swift.tvos.deployment_target = '9.0'

    swift.dependency 'OHHTTPStubs/Core'
    #additional dependency
    swift.dependency 'OHHTTPStubs/NSURLSession'
    swift.source_files = "OHHTTPStubs/Sources/Swift/*.swift"
  end
```

**Comment by AliSoftware** [comment]
I confirm what @Liquidsoul said.

 hat's totally intentional, so that people can only opt-in to what they need.

If we were doing the opposite (which is what you suggest), there wouldn't be a way to get the Swift wrapper subspec without the NSURLSession nor a way to opt-out other subspecs.

All the details, subspecs list and dependencies and rationale for how this is split in the various subspecs are explained in the README under the collapsible sections.

If people don't read the documentation, they should not expect to file a bug and get a fix, especially if the solution and its rationale has already been explained in multiple places.
