### ISSUE TITLE
Add OHHTTPStubs_HTTPBody to URLRequest in Swift

### ISSUE THREAD

**Issue by marcelofabri** [AliSoftware/OHHTTPStubs#215]
We should have a `OHHTTPStubs_HTTPBody` property in an `extension URLRequest` so the workaround in #212 is not needed

**Comment by marcelofabri** [comment]
I've updated to the latest version but it seems that something is wrong 😬 

```swift
let x = request.ohhttpStubs_httpBody
```

`Value of type 'URLRequest' has no member 'ohhttpStubs_httpBody'`

Here's how I'm importing on my Podfile:
```ruby
pod 'OHHTTPStubs', :subspecs => ['Default', 'Swift', 'NSURLSession']
```

Maybe it's happening because of this `#if` https://github.com/AliSoftware/OHHTTPStubs/blob/master/OHHTTPStubs/Sources/Swift/OHHTTPStubsSwift.swift#L31 ?

**Comment by AliSoftware** [comment]
Yeah, that's probably because of the `#if`.


What's strange is that this `#if` is also used by the UnitTests test suite to only run the test on this property if the corresponding subspec has been included (otherwise when we run `pod lib lint` or try to publish the pod, which rightfully tests _all_ the possible configurations of subspecs — including ones that don't include the `NSURLSession` subspec and this `OHHTTPStubs_HTTPBody` category — it fails at accessing this property when it doesn't exist.

So it _is_ necessary to only declare that `ohhttpStubs_httpBody` extension in Swift _only_ if the `OHHTTPStubs_HTTPBody` implementation exists (if the subspec has been imported), otherwise some configurations won't compile if they don't include the subspec.
But I'm not sure the trick I added with that `#if` does the job, especially since the macro is defined in ObjC but the `#if` is written in Swift and they don't share their macros.

---

I'm open to any suggestion as to how to fix this while still making it work for every configuration.

We could consider separating your extension in a dedicated Swift file and only include it in the `NSURLSession` subspec… but then for people still using ObjC and not using Swift they'll then start to have a Swift file and have to load the whole Swift runtime just for a thing they'll never use…
I don't think there's a way to include a file conditionally only if both `NSURLSession` and `Swift` subspecs have been activated and not include it otherwise…

I might consider re-organizing the subspecs at some point (who doesn't need `NSURLSession` support nowadays that `NSURLConnection` is long deprecated?) which could be a solution, but that would potentially break subspecs for some of people, so it's not an easy decision…

**Comment by marcelofabri** [comment]
This is probably overkill, but we could have a `SwiftNSURLSession` subspec that imported `Swift` and `NSURLSession` subspecs + this extension. However this seems a lot of trouble just to avoid one typecast 😬

**Comment by AliSoftware** [comment]
Yeah, and I know people would not understand all the complexity behind it ("why do I have to add the `SwiftNSURLSession` subspec when I already had `pod 'OHHTTPStubs/Swift'` before and it worked but now it's broken?") and this would require a lot of support time to answer those questions :wink:

Th two options I find acceptable so far:

* Revert your PR and remove that extension. After all, a cast is enough to reproduce the same behaviour (sure that's not as nice, but heh)
* Make `NSURLSession` part of the `Swift` subspec, so that we're now sure it's always included.

Given that some other people complain that adding `pod 'OHHTTPStubs/Swift'` to your `Podfile` is not enough and you have to include `pod 'OHHTTPStubs'` to it too otherwise you don't have `NSURLSession` nor `JSON` support… maybe it's time I revise my organisation of the subspecs after all. But I just need to make sure it's possible for everyone to opt-out of `NSURLSession` and `JSON` for people not wanting it, and be sure I don't disrupt existing projects which have declared certain subspecs in their `Podfile` and will end up with a project not working if that new subspecs organisation remove stuff from what they previously had in their Pods…

**Comment by marcelofabri** [comment]
Maybe we should revert that extension for now and think on a bigger subspecs reorganization. We can always make it a new major (`6.0.0`) so it'd be expected to have some breaking changes.

**Comment by AliSoftware** [comment]
Yeah, that's probably the best choice for now indeed.

**Comment by AliSoftware** [comment]
Reverted in 128f1b35ff3abae8ce56fdce2ece000e2ab1b109 until better solution :wink:

**Comment by marcelofabri** [comment]
Thanks! 💯
