### ISSUE TITLE
Swift Examples in "Stub requests with a file" section in wiki incorrect

### ISSUE THREAD

**Issue by zachlucas** [AliSoftware/OHHTTPStubs#218]
The current Swift example is:
```
// Swift
stub(isHost("mywebservice.com")) { request in
  // Stub it with our "wsresponse.json" stub file
  return OHHTTPStubsResponse(fileAtPath:OHPathForFile("wsresponse.json", self.dynamicType)!
    statusCode:200 headers:["Content-Type":@"application/json"])
}];
```

Should be:
```
// Swift
stub(isHost("mywebservice.com")) { request in
                // Stub it with our "wsresponse.json" stub file
                OHHTTPStubsResponse(fileAtPath:OHPathForFile("wsresponse.json", self.dynamicType)!, statusCode: 200, headers: ["Content-Type":"application/json"])
            }
```

**Comment by AliSoftware** [comment]
Why is that? The only difference I see in your correction is that:

* You removed the `return` statement
* You used the base name of the file (`wsresponse.json`) instead of its path (that my example constructs using the helper function `OHPathForFile` which basically simply does a `NSBundle.pathForResource(…)` call to get the path of the file in the current bundle)

Giving only the path isn't supposed to work (as in practice in 80% of cases you'll indeed place your JSON fixtures directly in your bundle, but nothing prevent you to place them elsewhere, like in a subdirectory, and you'll have to specify a matching different path in such cases instead) so I don't understand your fix.

**Comment by zachlucas** [comment]
Sorry, I've updated my comment.  Notice the last line of the original, it includes an errant `];`

**Comment by AliSoftware** [comment]
Oh, well spotted 👌  Fixed, thanks!
