### ISSUE TITLE
ohhttpStubs_HTTPBody() not available for swift 3.0

### ISSUE THREAD

**Issue by isimpson** [AliSoftware/OHHTTPStubs#222]
Currently no way to access the stubbed request body in swift 3.0 without first casting the request to NSURLRequest.
This works:
```
let req: NSURLRequest = request as NSURLRequest
let body = req.ohhttpStubs_HTTPBody()
```
This does not:
```
let body = request.ohhttpStubs_HTTPBody()
```

There was an attempt to fix this with PR: https://github.com/AliSoftware/OHHTTPStubs/pull/216
It seems that this was reverted as it was never working correctly.

**Comment by AliSoftware** [comment]
Yes it's a known issue without an easy solution that would work for _every_ subspec configuration so not sure we're gonna fix that, given how complex it could be to make it work for people using the subspec… while still not make the compilation failed for people not using it.

In the meantime the fix is easy: just cast your `request as NSURLRequest`. Not as pretty but easy enough and did the job until we find a configuration working for everybody without breaking compilation for others.

**Comment by isimpson** [comment]
Ok, thanks for the quick response. May be nice to leave this issue to help others with the current workaround:
`(request as NSURLRequest).ohhttpStubs_HTTPBody()`

**Comment by AliSoftware** [comment]
@isimpson Release 6.0.0 (#242) will finally fix this by finally making the Swift subspec always include NSURLSession so we were able to add the `hasBody()` matcher to the Swift API too!
