### ISSUE TITLE
WKWebView or UIWebView support？

### ISSUE THREAD

**Issue by WildDylan** [AliSoftware/OHHTTPStubs#227]
Hey, WKWebView or UIWebView support？

**Comment by AliSoftware** [comment]
`WKWebView` uses a separate process (to use the accelerated Javascript engine of iOS in a secure and sandboxed environment) so we have little to no control over it.

For example, it's not possible (Apple doesn't open anything in the API) to hook a custom `NSURLProtocol` in `WKWebView` from your application to stub requests, due to how `WKWebView` works and how it's isolated in its own closed process. This means that there's technically no way to implement `OHHTTPStubs` hooking in `WKWebView` (except if in the future Apple opens the API in `WKWebView` to configure custom `NSURLProtocols` for it, but I highly doubt it)

As for `UIWebView`, they normally use `NSURLConnection` under the hood so `OHHTTPStubs` stubs should work out of the box.

**Comment by WildDylan** [comment]
I use it [WKWebViewWithURLProtocol](https://github.com/WildDylan/WKWebViewWithURLProtocol) for custom URLProtocol hook request from WKWebView.

**Comment by AliSoftware** [comment]
Ah, interesting, thanks for the feedback.

## WKWebView

Will take a look at your pod, but as it seems to use a private API, so I won't probably integrate that in my own pod.
But we could totally point to your pod `WKWebViewWithURLProtocol` in the README — like in "Known Limitations" we could say that for `WKWebView` people could use your pod but would have to tweak it around to hope bypassing the validation on submission with selector hiding (and praying 😄)

## UIWebView

Did you manage to make it work for UIWebView? I remember having making it work myself a while ago, but didn't re-test it recently, so maybe something changed in latest versions of iOS?
I also discovered thanks to https://github.com/AliSoftware/OHHTTPStubs/issues/225#issuecomment-262476210 that there's a known Apple bug where requests from `UIWebView` to multimedia content (mp4, svg, …) don't go through the usual URL Loading System (so they bypass any registered custom `NSURLProtocol`), so if when testing with your code for this current issue you were in fact trying to stub multimedia content, that might be the reason. Could you give some details about what you tried to load/stub when trying with `UIWebView`?

Thx

**Comment by Ashton-W** [comment]
@AliSoftware what about providing WKWebView support through a pod subspec and/or preprocessor macro

**Comment by AliSoftware** [comment]
@Ashton-W Sadly, Some people want Carthage support. Which allows neither options.

**Comment by Ashton-W** [comment]
If it is a must to support binaries built without any configuration options we could create an additional target that adds this feature. Carthage users could link this additional framework?

**Comment by AliSoftware** [comment]
tbh, I'm not a Carthage user and don't know much about the possibilities we would have here

**Comment by WildDylan** [comment]
@AliSoftware Some times, i want to cache HTML sources in my documents folder, i want to load this as a website with stub.
