### ISSUE TITLE
Please set master to swift 3 :D

### ISSUE THREAD

**Issue by gperdomor** [AliSoftware/OHHTTPStubs#233]
Any reason why we master in still in swift 2.3?

**Comment by Liquidsoul** [comment]
Hi @gperdomor,

I suppose that you are talking about the Carthage configuration?

The rationale behind the current setup can be found in the comments of #192

Moving to swift 3 would require to keep a swift 2.3 compatibility anyway as the swift version is not enforced "yet". It should be soon when Xcode will drop the support for it.
Because of that, maybe it is better to keep things as-is for now and drop support of 2.3 altogether once Xcode stops supporting it.

Are you having a specific issue with this current setup? 😊

**Comment by piercifani** [comment]
Hello @Liquidsoul,

Yes, there is an issue here when you integrate this library using Carthage, since Carthage will use the project's `xcodeproj` to create a framework, and currently the project is set to compile with Swift 2.3 [check it here](https://github.com/AliSoftware/OHHTTPStubs/blob/master/OHHTTPStubs/OHHTTPStubs.xcodeproj/project.pbxproj#L1322).

In order to get this working with Carthage you'd have to fork it and change this value to `3.0`which is less than ideal.

Since Swift 2.3 is closer and closer to deprecation (Xcode 8.3 release could be less than a month away) I think it's safe to set Swift 3 as the default for this project.

Thanks!

**Comment by Liquidsoul** [comment]
Hi @piercifani,

We made things so you should not need to fork the repository to use Carthage and Swift 3.0.
As stated in the carthage part of [this section](https://github.com/AliSoftware/OHHTTPStubs/tree/swift-3.0#using-the-right-swift-version-of-ohhttpstubs-for-your-project), all you need to do is specify the `swift-3.0` branch in your `Cartfile` and you should be good to go 😃 

As Xcode 8.3 is coming soon, maybe it is a good time to work on the Swift 2.3 to Swift 3.0 migration of the project.

**Comment by Liquidsoul** [comment]
I forgot that you can also use dedicated releases for the library which have the `-swift3` suffix like [here](https://github.com/AliSoftware/OHHTTPStubs/releases/tag/5.2.3-swift3) for the latest one, and previous ones are available too!

**Comment by piercifani** [comment]
oops... sorry, I didn't catch that! Thanks a lot!

**Comment by AliSoftware** [comment]
Note that I think in a near future we will indeed make Swift3 the default (and keep Swift2.3 releases for people having legacy projects), as Swift3 is indeed now the default for most people and 2.3 is dropped with Xcode 8.3 anyway.

I just won't do a release just for that, but will wait until there's something to release to do that for the next version.

**Comment by ianbytchek** [comment]
Today is the day! 🥁🎉

**Comment by Liquidsoul** [comment]
I think we can finally close this 🍾🎉
