### ISSUE TITLE
OHHTTPStubs can't stub Alamofire

### ISSUE THREAD

**Issue by ugenlik** [AliSoftware/OHHTTPStubs#236]
Swift 3, Xcode 8.2.1

I know there are a couple of issues resolved in the past regarding this, but none of the suggested solutions worked for me.  (https://github.com/AliSoftware/OHHTTPStubs/issues/126)

1.)
![screen shot 2017-03-20 at 11 31 00 am](https://cloud.githubusercontent.com/assets/1995917/24107289/b98076b2-0d60-11e7-8f11-f0fc45eeb66e.png)

2.)
I don't call  `Alamofire.request`  at start up or in app delegate,  `Alamofire.request` is called after my app sends a login request.

Running following test  (login200.json is in  the test bundle)

```
    func testExample() {
        stub(condition: isHost("*********")) { request in
            return OHHTTPStubsResponse(
                fileAtPath: OHPathForFile("login200.json", type(of: self))!,
                statusCode: 200,
                headers: ["Content-Type":"application/json"]
            )
        }
        
        let expect = expectation(description: "Alamofire")
        
        LoginREST.loginWith(username: "dontmatter", password: "dontmatter") { (success, errorMessage) in
            if success == true
            {
                expect.fulfill()
            }
            else
            {
                XCTAssertNil(errorMessage, "Login error \(errorMessage)")
            }
        }
        
        waitForExpectations(timeout: 5.0, handler: nil)
    }
```

LoginREST class is 
```
class LoginREST{
    
    class func loginWith(username: String, password: String,
                   completionClosure: @escaping (_ isSuccesfull :Bool , _ error :String) ->())
    {
        let parameters: Parameters = [
            "type": "password",
            "username": username,
            "password": password
        ]
        
        
        Alamofire.request(******, method: .post, parameters: parameters).validate()
            .validate(contentType: ["application/json"])
            .responseJSON() { response in
                switch response.result {
                    
                case .success:
                    //debug print
                    if ProcessInfo.processInfo.environment["XCTestConfigurationFilePath"] == nil {
                        // Code only executes when tests are running
                        print("Validation Successful")
                    }

                    completionClosure(true,"")
                    
                    
                case .failure(let error):
                    // handle errors (including `validate` errors) here
                    print(error)
                    if let statusCode = response.response?.statusCode {
                        if statusCode == 401 {
                            print("yall")
                        }
                    }
                    completionClosure(false,"Invalid email and password combination")
                }
            }
```

I get 
```
responseValidationFailed(Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(401))
```

Obviously because of `username: "dontmatter", password: "dontmatter"` it sends and receives the actual response...

3.) I have added OHHTTPStubs to main project too (which I think is a terrible approach but it didn't solve the problem)

I think `OHHTTPStubs` is definitely getting called before any `Alamofire.` inits or requests

**Comment by AliSoftware** [comment]
Could you try the same request without Alamofire to check if it's related to Alamofire or not? 

Could you put breakpoints in the Alamofire code when the URLSession is created and one when OHHTTPStubs does list and do the swizzling to check the order when they are called? 
Or just right before performing what you think is your first Alamofire request, check at that point the Alamofire's own URLSession's `.configuration.protocolClasses` If it contains the OHHTTPStubs protocol

Also could you check if OHHTTPStubs is just not installed or if it's installed but your condition to stub your requests is wrong? For example maybe you used a condition of `isHost("http://example.com/")` (which is not a host string anyway) instead of `isHost("example.com")`.
You could for example replace your condition with a block always returning true, so it would stub all requests… and check with a breakpoint if the stub is called in that case. If that's the case that means the condition you use is incorrect.

**Comment by ugenlik** [comment]
I feel so dumb, you were right, Alamofire is fired before OHHTTPStubs, I missed a piece of code that runs to get app configs from the server before the login... My bad....

Thanks for the quick reply

**Comment by AliSoftware** [comment]
Cool that you found the source, thanks for taking the time to reply and close! 👍
