### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by Jerem42** [AliSoftware/OHHTTPStubs#256]
Just asking, when do you think OHHTTPStubs/Swift will be compatible with Swift 4?

Thanks for your amazing job.

**Comment by Liquidsoul** [comment]
Hi @Jerem42,

I have to admit that I did not try to use `OHHTTPStubs` with Swift 4 yet.
Can you give us some details on the issues you have when using `OHHTTPStubs` with Swift 4?

Thanks!

**Comment by Jerem42** [comment]
Sure, here's the error when I try to import OHHTTPStubs:

`Module compiled with swift 3.1 cannot be imported in Swift 4.0`

The same happen if the Swift language version in the Settings is 3.2.

**Comment by Liquidsoul** [comment]
Can you provide some details about the integration tool you are using and follow the [issue template](https://github.com/AliSoftware/OHHTTPStubs/blob/master/.github/ISSUE_TEMPLATE.md) and provide the informations it contains, please? 😊 

I suspect that you are using Carthage here and I am afraid that we may not be able to support every swift version in this case 😞

**Comment by AliSoftware** [comment]
Carthage is based on the idea of downloading the *pre-compiled binary* framework of each library you put in your Cartfile if available. Which is not a good idea until Swift is ABI stable (and discouraged by Apple for this exact reason) because then every time the compiler changes the Swift version then every binary framework is incompatible. 

If you're in this situation (using Carthage to integrate OHHTTPStubs) then OHHTTPStubs will not be the only framework you'll have this issue with (every library providing a precompiled version will have the same issue). You'll have to use the `--no-use-binaries` flag of Carthage to about this issue with OHHTTPStubs and all other libraries you use in your Cartfile. You can find more info in Carthage's own documentation & issues.

**Comment by ikesyo** [comment]
> You'll have to use the --no-use-binaries flag of Carthage to solve this issue with all other libraries you use in your Cartfile. You can find more info in Carthage's own documentation & issues.

FYI Carthage now falls back to build checked out projects if prebuilt binaries was built with different Swift version from local Swift version, so normally you will not need to add `--no-use-binaries` option.

**Comment by AliSoftware** [comment]
Just so we know if there's still work to do on that issue: has anybody had time to test OHHTTPStubs with Xcode 9 & Swift 4 and saw any compilation issue with it or code that would need modification for it to be adapted to Swift 4?

**Comment by gonzalezreal** [comment]
I am using OHHTTPStubs in a Swift 4 project (installed via Carthage) and I haven't experienced any issues using Xcode beta 4. I didn't install the latest beta yet.

**Comment by AliSoftware** [comment]
Cool, thanks @gonzalezreal for the feedback! 

I'm gonna close this one then.
We could still reopen it in case a later beta creates issues but I doubt it since the biggest risk was with the changes in the String API and the string manipulations we do in the matchers but we'd have seen errors by now if we were affected.
