### ISSUE TITLE
URLRequest.ohhttpStubs_HTTPBody() method not found

### ISSUE THREAD

**Issue by mplorentz** [AliSoftware/OHHTTPStubs#259]
### New Issue Checklist

- [x] I have tried with the latest version of OHHTTPStubs
- [x] I have read the [README](https://github.com/AliSoftware/OHHTTPStubs/blob/master/README.md)
- [x] I have read the [Using the right Swift Version of `OHHTTPStubs` for your project](https://github.com/AliSoftware/OHHTTPStubs#using-the-right-swift-version-of-ohhttpstubs-for-your-project) section
- [x] I have searched in the [existing issues](https://github.com/AliSoftware/OHHTTPStubs/issues?utf8=✓&q=is%3Aissue)
- [x] I have read [the OHHTTPStubs wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki) to see if there wasn't a detailed page talking about my issue

### Environment

- version of OHHTTPStubs: 6.0.0
- integration method you are using:
  * [x] Cocoapods
  * [ ] Carthage
  * [ ] submodule
  * [ ] other
- version of the tool you use: 1.3.1

### Issue Description

I am having trouble using the `ohhttpStubs_HTTPBody()` method on `URLRequest`. When I try to use it I get a compilation error: "Value of type 'URLRequest' has no member 'ohhttpStubs_HTTPBody'".

I am running Xcode 9.0 (9A235) and building a Swift 4 project. I have uploaded a sample project that exhibits the issue.
[ohhttpstubstest.zip](https://github.com/AliSoftware/OHHTTPStubs/files/1341959/ohhttpstubstest.zip)

It looks like this was an issue in Swift 3 (#222) and version 6.0.0 [was supposed to fix this issue](https://github.com/AliSoftware/OHHTTPStubs/pull/242).

The workaround given in #22 `(request as NSURLRequest).ohhttpStubs_HTTPBody()` *does* work for me, but I figured I would open a ticket since this is supposed to be fixed.

##### Complete output when you encounter the issue (if any)

```
Value of type 'URLRequest' has no member 'ohhttpStubs_HTTPBody'
```

**Comment by AliSoftware** [comment]
Hey @mplorentz, thanks for reporting the issue!

I believe you're right, I might have closed #222 too soon.
The big change which made me close #222 was that now the subspec `OHHTTPStubs/Swift` always includes other subspecs necessary to make it work for all configuration. But in fact #222 only makes it now possible to implement that now, but I haven't indeed exposed it entirely yet.

So since #222, I've added the `hasBody` matcher, so that you can now `stub(isHost("my-host.com") && hasBody(myBodyData)) { req in … }` — and this `hasBody` matcher is only possible thanks to #222 — but to access `ohhttpStubs_HTTPBody()` on `URLRequest` I indeed haven't exposed it to Swift in a nicer way than still forcing you to cast to `NSURLRequest` first.

I'll try to do a fix soon (probably re-applying parts of #216 — but without the `#if OHHTTPSTUBS_NSURLSESSION_HTTPBODY` lines which were not working as expected anyway)

**Comment by mplorentz** [comment]
I can take a shot at it. #216 looks easy enough to reimplement. I will try to submit a PR tomorrow.

**Comment by AliSoftware** [comment]
Cool, looking forward to it! 
(Don't forget to credit yourself in the CHANGELOG too!)

**Comment by AliSoftware** [comment]
@mplorentz just gave you push access to the repo so you can create your branch directly on it instead of having to fork 👍
