### ISSUE TITLE
Mock Response of Image upload on S3

### ISSUE THREAD

**Issue by msalmanST** [AliSoftware/OHHTTPStubs#272]
### New Issue Checklist

- [x] I have tried with the latest version of OHHTTPStubs
- [x] I have read the [README](https://github.com/AliSoftware/OHHTTPStubs/blob/master/README.md)
- [x] I have read the [Using the right Swift Version of `OHHTTPStubs` for your project](https://github.com/AliSoftware/OHHTTPStubs#using-the-right-swift-version-of-ohhttpstubs-for-your-project) section
- [x] I have searched in the [existing issues](https://github.com/AliSoftware/OHHTTPStubs/issues?utf8=✓&q=is%3Aissue)
- [x] I have read [the OHHTTPStubs wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki) to see if there wasn't a detailed page talking about my issue

### Environment

- version of OHHTTPStubs: [LIB VERSION HERE]
- integration method you are using:
  * [x] Cocoapods
  * [ ] Carthage
  * [ ] submodule
  * [ ] other
- version of the tool you use: [INSERT VERSION HERE]

### Issue Description

Hi, 

In the application I am working I am uploading image on s3 using aws ios sdk, I wanna confirm if there is a way my callback method can be triggered by OHHTTPStubs with stub response when I try to upload image.

1. Provide an image to 

##### Complete output when you encounter the issue (if any)

```

```

**Comment by Liquidsoul** [comment]
Hi @msalmanST,

Unfortunately, I do not think you can achieve that, data upload is one of the [known limitations](https://github.com/AliSoftware/OHHTTPStubs/blob/master/README.md#known-limitations) of `OHHTTPStubs`.
You may be able to intercept the request using `OHHTTPStubs` but you would not be able to give the expected response to the SDK.

Even if you manage to make this work, I would advise against this kind of configuration because you do not have the ownership of the AWS SDK code and any change in the library may break it.
The element you should mock is the SDK itself and have some kind of small abstraction layer over it. This would then be your mocking point for your tests.

**Comment by msalmanST** [comment]
@Liquidsoul Thanks for your quick response, I will look into it 👍
