### ISSUE TITLE
Is it possible to disable/log network calls if they are not mocked?

### ISSUE THREAD

**Issue by szymon-kazmierczak** [AliSoftware/OHHTTPStubs#276]
### New Issue Checklist

- [x] I have tried with the latest version of OHHTTPStubs
- [x] I have read the [README](https://github.com/AliSoftware/OHHTTPStubs/blob/master/README.md)
- [x] I have read the [Using the right Swift Version of `OHHTTPStubs` for your project](https://github.com/AliSoftware/OHHTTPStubs#using-the-right-swift-version-of-ohhttpstubs-for-your-project) section
- [x] I have searched in the [existing issues](https://github.com/AliSoftware/OHHTTPStubs/issues?utf8=✓&q=is%3Aissue)
- [x] I have read [the OHHTTPStubs wiki](https://github.com/AliSoftware/OHHTTPStubs/wiki) to see if there wasn't a detailed page talking about my issue

### Environment

- version of OHHTTPStubs: [6.1.0]
- integration method you are using:
  * [x] Cocoapods
  * [ ] Carthage
  * [ ] submodule
  * [ ] other
- version of the tool you use: [0.27.0]

### Issue Description

Is it possible to disable network calls if they are not mocked? 
I want to make sure that my test suite does not perform any network call that is not mocked - ideally log the cases where the mock is missing, with some additional info like URL. 

In another project I'm working on (Android app, using [RESTMock](https://github.com/andrzejchm/RESTMock), the mocking solution has its own IP/port (localhost and an empty port) and it intercepts all the calls being made and notifies the user when a mock is missing.

``` 
 E/RESTMock: <- Response ERROR:	NOT MOCKED: GET /api/settings/settings.json HTTP/1.1
                                            list of mocked requests:
                                           (HTTP method is: POST and url contains: /access/auth)
                                           (HTTP method is: GET and url starts with: /api/tickets.json) ```

**Comment by AliSoftware** [comment]
Hello

Yes it is totally possible.

Either by using a fallback stub, as explained [in the wiki here](https://github.com/AliSoftware/OHHTTPStubs/wiki/Usage-Examples#stack-multiple-stubs-and-remove-installed-stubs)…

Or better, since the last version ([6.1.0](https://github.com/AliSoftware/OHHTTPStubs/releases/tag/6.1.0)) there's even a dedicated method for that now, called `onStubMissing`. You can call it in the `setup` of your tests to tell what to do if a network request which is not subbed is encountered, so you can for example log a message, make your test fail, or fatalError, or make the request return an HTTP error for those unstubbed requests, etc.
