### ISSUE TITLE
Example project fails to build

### ISSUE THREAD

**Issue by benhirashima** [AliSoftware/OHHTTPStubs#94]
I can't get the example project to bulid. I'm using XCode 6.1.1. The error is:

ld: library not found for -lPods-OHHTTPStubs

If I remove -l"Pods-OHHTTPStubs" and $(inherited) from Other Linker Flags, I get

ld: library not found for -lPods

Couldn't figure out how to make that one go away.

**Comment by benhirashima** [comment]
The above happened when only opening the xcodeproject file. When I open the workspace, I get this error instead:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_OHHTTPStubs", referenced from:
      objc-class-ref in MainViewController.o
  "_OBJC_CLASS_$_OHHTTPStubsResponse", referenced from:
      objc-class-ref in MainViewController.o
  "_OHHTTPStubsDownloadSpeedWifi", referenced from:
      ___38-[MainViewController installTextStub:]_block_invoke_2 in MainViewController.o
      ___39-[MainViewController installImageStub:]_block_invoke_2 in MainViewController.o
ld: symbol(s) not found for architecture x86_64

BTW, I'm not using CocoaPods in case that wasn't already clear.

**Comment by AliSoftware** [comment]
The workspace compiles locally on my machine and on travis CI so that is probably some modification you did on your Mac.
You must indeed open the workspace to build the example, not the project (the error you got when opening the project alone without the workspace is totally normal, as the dependency between the example and OHHTTPStubs is provided by the workspace so that's what the workspace is for !)

Given your description you probably modified the project used by the workspace — typically you probably removed the dependency to `-lPods-OHHTTPStubs` in the project somehow — which would explain why the workspace now fails to build.

Simply rollback all your local changes (using GIT) — to make your local working copy go back to the same state as the github repo — and try again.

**Comment by AliSoftware** [comment]
Any news?

**Comment by benhirashima** [comment]
sorry, don't have time to look at this right now. i would just suggest you test it on a clean machine. it seems like the sample project is making some assumption about the environment that isn't true in my case.

**Comment by AliSoftware** [comment]
I confirm that I just did test on a clean machine, by doing `git clone https://github.com/AliSoftware/OHHTTPStubs.git` then opening the `Example/OHHTTPStubsDemo.xcworkspace` workspace in Xcode 6.3, and Build & Run works like a charm.

Given what you describe about what you did, I'm pretty sure that's a bad manipulation on your local clone (especially as you described that you removed `-l"Pods-OHHTTPStubs"` from the project, which you shouldn't have done and would totally explain the error you got)

I'm sure that if you remove your working copy and try cloning it again, it will work.
_(You can also use `pod try OHHTTPStubs` to let CocoaPods download/clone to repository for you in a temporary folder and opening the example workspace for you, so that ensures you got a clean copy)_
